version: "3"

services:
  # voice server
  shawarma:
    build: ./shawarma

    environment:
      - WEBRTC_LISTEN_IP=127.0.0.1
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
  # backend
  kousa:
    build: ./kousa
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres
      - BEN_GITHUB_ID=benawad
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - GITHUB_CLIENT_ID=5d5xxxxxxab70
      - GITHUB_CLIENT_SECRET=48xxxxxxxxxxxxd1cd5
      - TWITTER_SECRET_KEY=testtwittersecret
      - TWITTER_BEARER_TOKEN=testtwitterbearer
      - TWITTER_API_KEY=testtwitterkey
      - DISCORD_CLIENT_ID=testdiscordkey
      - DISCORD_CLIENT_SECRET=testdiscordkey
      - GOOGLE_CLIENT_SECRET=testdiscordkey
      - GOOGLE_CLIENT_ID=testdiscordkey
      - ACCESS_TOKEN_SECRET=8f51exxxxxx7211dd
      - SENTRY_DSN=SIJHFIUSDHIF
      - SECRET_KEY_BASE=TESTING
      - REFRESH_TOKEN_SECRET=dbb85xxxxxx9ebde
      - WEB_URL=http://localhost:3000
      - API_URL=http://localhost:4001
      - PORT=4001
    ports:
      - 4001:4001
  postgres:
    image: postgres:13-alpine
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRE_DB=postgres
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: erlang_dev_only_cookie
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 60s
      timeout: 5s
